cmake_minimum_required(VERSION 3.14)

add_executable(lab03_task1 task1.cpp)
add_executable(lab03_task2 task2.cpp)
add_executable(lab03_task3 task3.cpp)
add_executable(lab03_task4 task4.cpp)
add_executable(lab03_task5 task5.cpp)
add_executable(lab03_task6 task6.cpp)
add_executable(lab03_task7 task7.cpp)
add_executable(lab03_task8 task8.cpp)
add_executable(lab03_task9 task9.cpp)
add_executable(lab03_task10 task10.cpp)
add_executable(lab03_task11 task11.cpp)
add_executable(lab03_task12 task12.cpp)
add_executable(lab03_task13 task13.cpp)
add_executable(lab03_task14 task14.cpp)
add_executable(lab03_task15 task15.cpp)
add_executable(lab03_task16_contest task16_contest.cpp)
add_executable(lab03_task16_submit task16_submit.cpp)
add_executable(lab03_task17_contest task17_contest.cpp)
add_executable(lab03_task17_submit task17_submit.cpp)
add_executable(lab03_task18 task18.cpp)
add_executable(lab03_task19 task19.cpp)
add_executable(lab03_task20 task20.cpp)
add_executable(lab03_task21 task21.cpp)
