cmake_minimum_required(VERSION 3.14)

add_executable(lab10_task1 task1.cpp)
add_executable(lab10_task2 task2.cpp)
add_executable(lab10_task3_1 task3_1.cpp)
add_executable(lab10_task3_2 task3_2.cpp)
add_executable(lab10_task3_3 task3_3.cpp)
add_executable(lab10_task3_4 task3_4.cpp)
add_executable(lab10_task3_5 task3_5.cpp)
add_executable(lab10_task4 task4.cpp)
add_executable(lab10_task5 task5.cpp)
add_executable(lab10_task6 task6.cpp)
add_executable(lab10_task7_1 task7_1.cpp)
add_executable(lab10_task7_2 task7_2.cpp)
add_executable(lab10_task8_1 task8_1.cpp)
add_executable(lab10_task8_2 task8_2.cpp)
add_executable(lab10_task9 task9.cpp)
add_executable(lab10_task10 task10.cpp)
add_executable(lab10_task_submit
        task_submit/main.cpp
        task_submit/task.cpp
        task_submit/task.h
)