cmake_minimum_required(VERSION 3.14)

add_executable(lab02_task1 task1.cpp)
add_executable(lab02_task2 task2.cpp)
add_executable(lab02_task3 task3.cpp)
add_executable(lab02_task4 task4.cpp)
add_executable(lab02_task5 task5.cpp)
add_executable(lab02_task6 task6.cpp)
add_executable(lab02_task7 task7.cpp)
add_executable(lab02_task8 task8.cpp)
add_executable(lab02_task9 task9.cpp)
add_executable(lab02_task10 task10.cpp)
add_executable(lab02_task11 task11.cpp)
add_executable(lab02_task12 task12.cpp)
add_executable(lab02_task13 task13.cpp)
add_executable(lab02_task14 task14.cpp)
add_executable(lab02_task15 task15.cpp)