cmake_minimum_required(VERSION 3.14)

add_executable(lab01_task_submit
        task_submit/main.cpp
        task_submit/Employee/Employee.cpp
        task_submit/Employee/Employee.h
        task_submit/Array/Array_func.h
        task_submit/Array/Array_func.cpp
        task_submit/Vector/Vector_func.h
        task_submit/Vector/Vector_func.cpp
)