cmake_minimum_required(VERSION 3.14)

add_executable(lab09_task1 task1.cpp)
add_executable(lab09_task2 task2.cpp)
add_executable(lab09_task3 task3.cpp)
add_executable(lab09_task4 task4.cpp)
add_executable(lab09_task5 task5.cpp)
add_executable(lab09_task6 task6.cpp)
add_executable(lab09_task7 task7.cpp)
add_executable(lab09_task8 task8.cpp)
add_executable(lab09_task9 task9.cpp)
add_executable(lab09_task10 task10.cpp)
add_executable(lab09_task11_contest task11_contest.cpp)
add_executable(lab09_task11_submit task11_submit.cpp)
add_executable(lab09_task12 task12.cpp)
add_executable(lab09_task13 task13.cpp)
add_executable(lab09_task14 task14.cpp)