cmake_minimum_required(VERSION 3.14)

add_executable(lab12_task1 contest/task1.cpp)
add_executable(lab12_task2 contest/task2.cpp)
add_executable(lab12_task3 contest/task3.cpp)
add_executable(lab12_task4 contest/task4.cpp)
add_executable(lab12_task5 contest/task5.cpp)
add_executable(lab12_task6 contest/task6.cpp)
add_executable(lab12_task7 contest/task7.cpp)
add_executable(lab12_task8 contest/task8.cpp)
add_executable(lab12_task9 contest/task9.cpp)
add_executable(lab12_task10 contest/task10.cpp)
add_executable(lab12_task11 contest/task11.cpp)
add_executable(lab12_task12 contest/task12.cpp)
add_executable(lab12_task13 contest/task13.cpp)
add_executable(lab12_task6_submit task6/task6.cpp)
add_executable(lab12_task10_submit task10/task10.cpp)