cmake_minimum_required(VERSION 3.14)

add_executable(lab08_task1-2 task1-2.cpp)
add_executable(lab08_task3-4 task3-4.cpp)
add_executable(lab08_task5-6 task5-6.cpp)
add_executable(lab08_task7-8 task7-8.cpp)
add_executable(lab08_task9-10 task9-10.cpp)
add_executable(lab08_task11 task11.cpp)
add_executable(lab08_task12 task12.cpp)
add_executable(lab08_task13 task13.cpp)
add_executable(lab08_task
        task_submit/main.cpp
        task_submit/array_funcs.cpp
)